name: APP (Vue)

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
      working-directory: ./web
      codeCov-token: ${{ secrets.CodeCov }}

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
        working-directory: ${{env.working-directory}}
      - run: npm run build --if-present  --tag web
        working-directory: ${{env.working-directory}}

      - name: Docker Build Backend Image
        working-directory: ${{env.WORKING_DIRECTORY}}
        run: |      
          docker build --tag web . --file web/Dockerfile
          docker tag web artifacts.developer.gov.bc.ca/cac1-cas/${{ env.IMAGE_NAME }}:dev-${{ steps.short_sha.outputs.SHORT_SHA }}
          # docker compose build backend
          # docker tag cas-web artifacts.developer.gov.bc.ca/cac1-cas-web/${{ env.IMAGE_NAME }}:dev-${{ steps.short_sha.outputs.SHORT_SHA }}
          
